from pathlib import Path

APPLICATION_NAME = "Workouts Tracking"
INSTALL_DIR = Path(__file__).resolve().parent.parent
TESTS_DIR = INSTALL_DIR / "tests"
CODE_DIR = INSTALL_DIR / "workouts_tracking"

DATABASE_TABLES = {
    # dictionary of the name of the tables and its columns
    # ("name": ["column_name type", "primary key (id)"])
    "measure_type": ["id integer not null",
                     "name text",
                     "unit text",
                     "primary key (id)",
                     ],
    "category": ["id integer not null",
                 "name text",
                 "primary key (id)",
                 ],
    "difficulty": ["id integer not null",
                   "name text",
                   "primary key (id)",
                   ],
    "workout": ["id integer not null",
                "date text",
                "start_time text",
                "end_time text",
                "comment text",
                "primary key (id)",
                ],
    "exercise": ["id integer not null",
                 "name text",
                 "command text",
                 "url text",
                 "category_id integer",
                 "difficulty_id integer",
                 "primary key (id)",
                 "foreign key (category_id) references category(id)",
                 "foreign key (difficulty_id) references difficulty(id)",
                 ],
    "muscle_group": ["id integer not null",
                     "name text",
                     "primary key (id)",
                     ],
    "exercise_muscle_group": ["exercise_id integer not null",
                              "muscle_group_id integer not null",
                              "primary key (exercise_id, muscle_group_id)",
                              "foreign key (exercise_id) references exercise(id)",
                              "foreign key (muscle_group_id) references muscle_group(id)",
                              ],
    "exe_exercise": ["workout_id integer not null",
                     "no_exe_exercise integer not null",
                     "exercise_id integer",
                     "comment text",
                     "primary key (workout_id, no_exe_exercise)",
                     "foreign key (workout_id) references workout(id)",
                     "foreign key (exercise_id) references exercise(id)",
                     ],
    "measure": ["id integer not null",
                "name text",
                "type_id integer",
                "per_set integer check (per_set = 0 or per_set = 1)",
                "exercise_id integer",
                "primary key (id)",
                "foreign key (type_id) references measure_type(id)",
                "foreign key (exercise_id) references exercise(id)",
                ],
    "performance": ["workout_id integer not null",
                    "no_exe_exercise integer not null",
                    "measure_id integer not null",
                    "value text",
                    "primary key (workout_id, no_exe_exercise, measure_id)",
                    "foreign key (workout_id) references workout(id)",
                    "foreign key (no_exe_exercise) references exe_exercise(no_exe_exercise)",
                    "foreign key (measure_id) references measure(id)",
                    ],
}
